export enum ApplicationStatus {
  PENDING = 'PENDING',
  TO_BE_PAID = 'TO_BE_PAID',
  PAID = 'PAID',
  REJECTED = 'REJECTED',
  ACCEPTED = 'ACCEPTED',
  ACCEPTED_RESERVE = 'ACCEPTED_RESERVE',
  MORE_INFO_NEEDED = 'MORE_INFO_NEEDED',
}